# Generated by Django 2.2.28 on 2022-12-14 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.BigIntegerField()),
                ('provider_name', models.BigIntegerField()),
                ('provider_state', models.BigIntegerField()),
                ('provider_city', models.BigIntegerField()),
                ('provider_location_count', models.BigIntegerField()),
                ('provider_type', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=256)),
                ('category_description', models.TextField()),
                ('category_name', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('type', models.BinaryField()),
                ('email', models.EmailField(max_length=254)),
                ('organization_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.BigIntegerField()),
                ('vendor_name', models.TextField()),
                ('vendor_revenue', models.BigIntegerField()),
                ('vendor_url', models.URLField()),
                ('vendor_category_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.BigIntegerField()),
                ('review_category_score', models.BigIntegerField()),
                ('provider_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_provider_id', to='home.Providers')),
                ('review_category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_review_category', to='home.Service_Category')),
                ('reviewer_type', models.ManyToManyField(blank=True, related_name='reviews_reviewer_type', to='home.Users')),
                ('vendor_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_vendor_id', to='home.Vendors')),
            ],
        ),
    ]
